// Code generated
// This file is a generated precompile contract test with the skeleton of test functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

package ibc

import (
	"math/big"
	"testing"

	"github.com/cosmos/ibc-go/v7/modules/core/exported"
	"github.com/ethereum/go-ethereum/common"
	"github.com/stretchr/testify/require"

	"github.com/ava-labs/subnet-evm/core/state"
	"github.com/ava-labs/subnet-evm/precompile/contract"
	"github.com/ava-labs/subnet-evm/precompile/testutils"
	"github.com/ava-labs/subnet-evm/vmerrs"
)

// TestRun tests the Run function of the precompile contract.
// These tests are run against the precompile contract directly with
// the given input and expected output. They're just a guide to
// help you write your own tests. These tests are for general cases like
// allowlist, readOnly behaviour, and gas cost. You should write your own
// tests for specific cases.
func TestRun(t *testing.T) {
	tests := map[string]testutils.PrecompileTest{
		"readOnly createClient should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				// CUSTOM CODE STARTS HERE
				// populate test input here
				testInput := CreateClientInput{}
				input, err := PackCreateClient(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: CreateClientGasCost,
			ReadOnly:    true,
			ExpectedErr: vmerrs.ErrWriteProtection.Error(),
		},
		"insufficient gas for createClient should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				// CUSTOM CODE STARTS HERE
				// populate test input here
				testInput := CreateClientInput{}
				input, err := PackCreateClient(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: CreateClientGasCost - 1,
			ReadOnly:    false,
			ExpectedErr: vmerrs.ErrOutOfGas.Error(),
		},
		"client id stored properly": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				testInput := CreateClientInput{
					ClientType: exported.Tendermint,
				}
				input, err := PackCreateClient(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: CreateClientGasCost,
			ReadOnly:    false,
			ExpectedRes: func() []byte {
				res, err := PackCreateClientOutput("07-tendermint-0")
				if err != nil {
					panic(err)
				}
				return res
			}(),
			AfterHook: func(t testing.TB, state contract.StateDB) {
				nextClientId := getStoredNextClientSeq(state)
				require.EqualValues(t, big.NewInt(1), nextClientId)
			},
		},
	}
	// Run tests.
	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			test.Run(t, Module, state.NewTestStateDB(t))
		})
	}
}
